
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Kuis1 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis1
     */
    public Kuis1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Proses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        Nama = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        Matpel = new javax.swing.JTextField();
        Nilai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 80, 51, 20);

        jLabel2.setText("Absen");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 150, 44, 20);

        jLabel3.setText("Matpel");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 220, 46, 20);

        jLabel4.setText("Nilai");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 280, 31, 20);

        Proses.setText("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        getContentPane().add(Proses);
        Proses.setBounds(160, 330, 79, 29);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 370, 270, 140);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(190, 76, 160, 40);
        getContentPane().add(Absen);
        Absen.setBounds(190, 136, 160, 40);

        Matpel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatpelActionPerformed(evt);
            }
        });
        getContentPane().add(Matpel);
        Matpel.setBounds(190, 200, 160, 40);
        getContentPane().add(Nilai);
        Nilai.setBounds(190, 266, 160, 40);

        jLabel5.setText("Penilaian Siswa");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 10, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void MatpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatpelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatpelActionPerformed

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed

// TODO add your handling code here:
String nama = Nama.getText();
Nama.setText(nama);
String absen = Absen.getText();
Absen.setText(absen);
String matpel = Matpel.getText();
Matpel.setText(matpel);
int nilai = Integer.parseInt(Nilai.getText());

if (nilai < 75) {
    TA.setText("Nama :"+nama+"\nAbsen :"+absen+"\nMatpel :"+matpel+"\nNilai :"+nilai+"\nKeterangan : Tidak lulus");

}else if (nilai > 75) {
     TA.setText("Nama :"+nama+"\nAbsen :"+absen+"\nMatpel :"+matpel+"\nNilai :"+nilai+"\nKeterangan : Lulus");
     
}else if (nilai == 100) {
     TA.setText("Nama :"+nama+"\nAbsen :"+absen+"\nMatpel :"+matpel+"\nNilai :"+nilai+"\nKeterangan : Sempurna");
     
}else if (nilai < 100) {
     TA.setText("Nama :"+nama+"\nAbsen :"+absen+"\nMatpel :"+matpel+"\nNilai :"+nilai+"\nKeterangan : Amazing");
       
        
        }


    }//GEN-LAST:event_ProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextField Matpel;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nilai;
    private javax.swing.JButton Proses;
    private javax.swing.JTextArea TA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
